# hipfile
[components.lib."storage-libs/hipfile/stage"]
include = [
  "share/hipfile/**",
]
[components.run."storage-libs/hipfile/stage"]
include = [
  "bin/**",
]
[components.dbg."storage-libs/hipfile/stage"]
[components.dev."storage-libs/hipfile/stage"]
[components.doc."storage-libs/hipfile/stage"]

# Tests
[components.test."storage-libs/hipfile/stage"]
optional = true
