# mivisionx
[components.lib."cv-libs/mivisionx/stage"]
[components.dbg."cv-libs/mivisionx/stage"]
[components.dev."cv-libs/mivisionx/stage"]
[components.doc."cv-libs/mivisionx/stage"]
[components.test."cv-libs/mivisionx/stage"]
include = [
  "share/mivisionx/**",
]
