# ocl-clr
[components.dbg."core/ocl-clr/stage"]
[components.dev."core/ocl-clr/stage"]
[components.doc."core/ocl-clr/stage"]
[components.lib."core/ocl-clr/stage"]
include = [
  "share/ocl/**",
]
[components.run."core/ocl-clr/stage"]
include = [
  "bin/**",
]
