# rocjitsu
[components.lib."emulation/rocjitsu/stage"]
default_patterns = false
include = [
  "lib/librocjitsu_kmd.so",
]
[components.dbg."emulation/rocjitsu/stage"]
[components.dev."emulation/rocjitsu/stage"]
[components.run."emulation/rocjitsu/stage"]
include = [
  "share/rocjitsu/**",
]
